### ISSUE TITLE
Teensy 4 (SmartMatrix Library 4.0) Todo List

### ISSUE THREAD

**Issue by embedded-creations** [pixelmatix/SmartMatrix#124]
- [x] `PANEL_32_PIXELDATA_TRANSFER_MAXIMUM_NS` computation
  - Adding APA102 refresh requires increasing this value (e.g. +220 for 64x64 HUB75, +250 for 128x64), what's a good default, and what's a good way of increasing it when needed? (constant or scaling with FLEXIO_CLOCK_DIVIDER?)
  - (Eric) I think that a good compromise which seems stable with some margin is using `FLEXIO_CLOCK_DIVIDER = 26` and `PANEL_32_PIXELDATA_TRANSFER_MAXIMUM_NS += 200`, which appears glitch free for me with a 128x128 HUB75 matrix plus 128x64 APA102 matrix, and still allows 120 FPS refresh rate at 48 bit refresh depth.
- [x] Glitching - occasional pair of lines for one frame only - when APA102 LEDs added
  - (Eric) confirmed same issue
- [x] <256 pixel limit per row on HUB75 panels?
  - 128x128 doesn't work, 120x128 does (I assume 256x128 doesn't work but 248x128 does).
  - Likely with Teensy 3 as well
  - (Eric) I am not able to reproduce this problem. FeatureDemo and FastLED_Panel_Plus_APA work at 128x128 and 256x128 for me. **kMatrixWidth and kMatrixHeight should be declared uint16_t in the sketch.**
- [x] Bring FlexIO_t4 library into SmartMatrix Library (with proper attribution)
  - We want SmartMatrix Library to be available through Arduino Library Manager, and FlexIO_t4 is not available that way.  Also, FlexIO_t4 likely needs to be modified to work around APA buffer cache flush issue
- [x] MultiRowRefreshMapping Teensy 4 support
- [x] Consider setting Teensy 4 HUB75 default refresh rate to 240 instead of 120
- [x] Allow changing APA102 clock rate from sketch
- [x] Allow lower color depth to increase display size / refresh rate across all platforms, not only for Teensy 4

ESP32 Todos (would be nice to have done for a major release):

- [x] Remove unfinished ESP32 APA102 classes
- [x] Scrolling text speed is maximum one pixel shift per frame, which is quite slow with slow calculation framerates - need to allow scrolling text more than once per frame?
- [x] Scrolling text has been reported to be scrolling backwards
- [x] Scrolling and Indexed layers are inefficient enough that they can lower the overall refresh rate
